## Random Forest

### 1. imbalance data의 학습: 빅데이터 처리:179-186

In [3]:
from sklearn.datasets import load_iris
from sklearn.metrics import accuracy_score #분석결과의 acuuracy 측정
#정확도: Accuracy는 전체 샘플의 개수들 중에서 얼마나 나의 알고리즘이 정답이라고 예측한 샘플이 포함되었는지의 비율을 의미한다. 예를 들어서, 내 알고리즘이 90% 정확하다면, 100개의 샘플들 중에서 90개만 정확하게 분류 하는 것이다.
import numpy as np
#numpy: 파이썬 언어를 위한 행렬,벡터 수학계산 위한 패키지
import pandas as pd

In [4]:
iris = load_iris() #iris데이터 불러오기

In [5]:
#trainig data 설정
x_train = iris.data[:-30]#데이터의 시작부터 끝에서 30번째 하나 전까지를 선택
y_train = iris.target[:-30]
 
#test data 설정
x_test = iris.data[-30:]#test feature data ##feature->학습 및 예측을 할 데이터의 특징, 항목 들
y_test = iris.target[-30:]#iris에서 target 데이터를 호출


In [6]:
y_train

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [7]:
y_test

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2])

#### Random Forest 분류기 생성 

In [8]:
from sklearn.ensemble import RandomForestClassifier
#Random Forest 분류기 생성을 위해 RandomForestClassifier 클래스를 import
#Sklearn.ensemble 모듈은 분류, 회귀 및 이상 탐지를 위한 ensemble-based 방법을 포함

In [9]:
#10개의 tree를 가진 random forest생성
rfc = RandomForestClassifier(n_estimators=10)
rfc
# n_estimators : Decision Tree의 개수 (default=10)
# 이거 뭔가 잘 안나와 왕이라노


RandomForestClassifier(n_estimators=10)

#### Random Forest 분류기

In [10]:
#입력 데이터를 이용해 분류기 학습입력 데이터를 이용해 분류기 학습
#fit 데이터를 줄테니 모델을 만들어!
rfc.fit(x_train, y_train)

#test data를 입력해 target data를 예측
prediction = rfc.predict(x_test)

#예측결과 prediction 과 실제 test data의 target비교
print(prediction == y_test)



[ True False  True False  True  True False False  True False  True  True
  True False False  True  True  True False  True  True  True  True  True
  True  True  True  True  True  True]


####  Random Forest 분류기 성능 평가 (1)

In [11]:
#random forest 정확도 측정
rfc.score(x_test, y_test)#정확도를 계산하는 함수
# x_test : 테스트 데이터 feature 값
# y_test : 테스트 데이터 target 값

0.7333333333333333

#### Random Forest 분류기 성능 평가 (2)


In [13]:
from sklearn.metrics import classification_report
import numpy as np

print("Accuracy is :", accuracy_score(prediction, y_test))
print(classification_report(y_test,prediction))
# y_test : 테스트 데이터 target 값
# prediction : 테스트 데이터의 target 예측 값
#accuracy_score() : 분류 결과의 accuracy를 계산 
#classification_report(): 분류 결과의 precision recall을 계산

Accuracy is : 0.7333333333333333
              precision    recall  f1-score   support

           1       0.00      0.00      0.00         0
           2       1.00      0.73      0.85        30

    accuracy                           0.73        30
   macro avg       0.50      0.37      0.42        30
weighted avg       1.00      0.73      0.85        30

C:\Users\Admin\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


## 2. balace data 학습
 2. balace data 학습
## Random forest  성능 제고 방법
### 강의자료 187~188 페이지


#### training, Test데이터 재생성

In [19]:
from sklearn.model_selection import train_test_split
x = iris.data
y = iris.target
X_train, X_test, Y_train, Y_test = train_test_split(x, y, test_size = 0.2)
print(y_test)
print(Y_test)

[0 0 0 1 2 2 2 0 2 0 2 0 0 0 1 0 2 2 1 2 2 2 0 0 2 2 0 1 0 2]
[0 1 2 2 2 0 1 1 2 2 0 0 1 0 2 1 1 0 0 2 1 1 1 1 1 1 0 1 1 0]
